name: Planting tomatoes
rules:
  - { image: PlotBeforeWithFarmer.png    , when: { black: 2, blue: 0, green: 0, red: 0 } } 
  - { image: PlotBefore.png              , when: { black: 0, blue: 0, green: 0, red: 0 } } 
  - { image: SeededPlotWithFarmer.png    , when: { black: 2, blue: 0, green: 1, red: 0 } } 
  - { image: SeededPlot.png              , when: { black: 0, blue: 0, green: 1, red: 0 } } 
  - { image: PlotWithTomatosAndFarmer.png, when: { black: 2, blue: 1, green: 0, red: 1 } } 
  - { image: PlotWithTomatos.png         , when: { black: 0, blue: 1, green: 0, red: 1 } } 
  - { image: HarvestedPlotWithFarmer.png , when: { black: 2, blue: 1, green: 0, red: 0 } } 
  - { image: HarvestedPlot.png           , when: { black: 0, blue: 1, green: 0, red: 0 } } 
  - { image: BarnAndFarmer.png           , when: { black: 3, blue: 0, green: 0, red: 0 } } 
  - { image: Barn.png                    , when: { black: 1, blue: 0, green: 0, red: 0 } } 
