name: Introduction

inherit:
  $course: gobstonesgames/quell
  $assets:
    extra: true
    attires:
      - Quell
  execution_speed: true
  source: true
  library: true
  board: true
  attire: true
  blocks: true