name: Quell
rules:
  - { image: Ball.png      , when: { black: '*', blue: 1, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 2, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 3, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 4, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 5, green: '*', red: '*' } }
  - { image: Ball-North.png, when: { black: '*', blue: 6, green: '*', red: '*' } }
  - { image: Ball-East.png , when: { black: '*', blue: 7, green: '*', red: '*' } }
  - { image: Ball-South.png, when: { black: '*', blue: 8, green: '*', red: '*' } }
  - { image: Ball-West.png , when: { black: '*', blue: 9, green: '*', red: '*' } }
  - { image: Empty.png     , when: { black:   0, blue: 0, green:   0, red:   0 } }
  - { image: Pearl.png     , when: { black:   1, blue: 0, green:   0, red:   0 } }
  - { image: Wall.png      , when: { black:   2, blue: 0, green:   0, red:   0 } }
  - { image: Wall.png      , when: { black:   2, blue: 0, green:   1, red: '*' } }
  - { image: LimitH-N.png  , when: { black:   4, blue: 0, green:   1, red:   9 } }
  - { image: LimitH-S.png  , when: { black:   4, blue: 0, green:   3, red:   9 } }
  - { image: LimitV-E.png  , when: { black:   4, blue: 0, green:   2, red:   9 } }
  - { image: LimitV-W.png  , when: { black:   4, blue: 0, green:   4, red:   9 } }
  - { image: CornerNW.png  , when: { black:   4, blue: 0, green: '*', red:   2 } }
  - { image: CornerNE.png  , when: { black:   4, blue: 0, green: '*', red:   3 } }
  - { image: CornerSW.png  , when: { black:   4, blue: 0, green: '*', red:   1 } }
  - { image: CornerSE.png  , when: { black:   4, blue: 0, green: '*', red:   4 } }
  - { image: AngleNW.png   , when: { black:   4, blue: 0, green: '*', red:   7 } }
  - { image: AngleNE.png   , when: { black:   4, blue: 0, green: '*', red:   8 } }
  - { image: AngleSW.png   , when: { black:   4, blue: 0, green: '*', red:   6 } }
  - { image: AngleSE.png   , when: { black:   4, blue: 0, green: '*', red:   5 } }
  - { image: Out.png       , when: { black:  10, blue: 0, green: '*', red: '*' } }
  - { image: TopEmpty.png  , when: { black: 100, blue: 0, green: '*', red: '*' } }
  - { image: TopNum00.png  , when: { black: 101, blue: 0, green: '*', red:   0 } }
  - { image: TopNum01.png  , when: { black: 101, blue: 0, green: '*', red:   1 } }
  - { image: TopNum02.png  , when: { black: 101, blue: 0, green: '*', red:   2 } }
  - { image: TopNum03.png  , when: { black: 101, blue: 0, green: '*', red:   3 } }
  - { image: TopEmpty.png  , when: { black: 101, blue: 0, green: '*', red: '*' } }
  - { image: TopMin03.png  , when: { black: 102, blue: 0, green: '*', red:   3 } }
  - { image: TopEmpty.png  , when: { black: 102, blue: 0, green: '*', red: '*' } }
  - { image: TopEmpty.png  , when: { black: 103, blue: 0, green: '*', red: '*' } }
  - { image: TopEmpty.png  , when: { black: 104, blue: 0, green: '*', red: '*' } }
  - { image: TopSolved.png , when: { black: 105, blue: 0, green: '*', red:   0 } }
  - { image: TopEmpty.png  , when: { black: 105, blue: 0, green: '*', red: '*' } }
