name: Quell
rules:
  - { image: Ball.png      , when: { black: '*', blue: 1, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 2, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 3, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 4, green: '*', red: '*' } }
  - { image: Ball.png      , when: { black: '*', blue: 5, green: '*', red: '*' } }
  - { image: Empty.png     , when: { black:   0, blue: 0, green:   0, red:   0 } }
  - { image: Pearl.png     , when: { black:   1, blue: 0, green:   0, red:   0 } }
  - { image: Wall.png      , when: { black:   2, blue: 0, green:   0, red:   0 } }
  - { image: Wall.png      , when: { black:   2, blue: 0, green:   1, red: '*' } }
  - { image: Out.png       , when: { black:  10, blue: 0, green:   0, red:   0 } }
  - { image: Out.png       , when: { black: 110, blue: 0, green: '*', red: '*' } }
