name: Quell
rules:
  - { image: Ball.png       , when: { black: '*', blue: 1, green: '*', red: '*' } }
  - { image: Ball.png       , when: { black: '*', blue: 2, green: '*', red: '*' } }
  - { image: Ball.png       , when: { black: '*', blue: 3, green: '*', red: '*' } }
  - { image: Ball.png       , when: { black: '*', blue: 4, green: '*', red: '*' } }
  - { image: Ball.png       , when: { black: '*', blue: 5, green: '*', red: '*' } }
  - { image: Ball-North.png , when: { black: '*', blue: 6, green: '*', red: '*' } }
  - { image: Ball-East.png  , when: { black: '*', blue: 7, green: '*', red: '*' } }
  - { image: Ball-South.png , when: { black: '*', blue: 8, green: '*', red: '*' } }
  - { image: Ball-West.png  , when: { black: '*', blue: 9, green: '*', red: '*' } }
  - { image: Empty.png      , when: { black:   0, blue: 0, green:   0, red:   0 } }
  - { image: Pearl.png      , when: { black:   1, blue: 0, green:   0, red:   0 } }
  - { image: Wall.png       , when: { black:   2, blue: 0, green:   0, red:   0 } }
  - { image: Wall.png       , when: { black:   2, blue: 0, green:   1, red: '*' } }
  - { image: LimitH-N.png   , when: { black:   4, blue: 0, green:   1, red:   9 } }
  - { image: LimitH-S.png   , when: { black:   4, blue: 0, green:   3, red:   9 } }
  - { image: LimitV-E.png   , when: { black:   4, blue: 0, green:   2, red:   9 } }
  - { image: LimitV-W.png   , when: { black:   4, blue: 0, green:   4, red:   9 } }
  - { image: CornerNW.png   , when: { black:   4, blue: 0, green: '*', red:   2 } }
  - { image: CornerNE.png   , when: { black:   4, blue: 0, green: '*', red:   3 } }
  - { image: CornerSW.png   , when: { black:   4, blue: 0, green: '*', red:   1 } }
  - { image: CornerSE.png   , when: { black:   4, blue: 0, green: '*', red:   4 } }
  - { image: AngleNW.png    , when: { black:   4, blue: 0, green: '*', red:   7 } }
  - { image: AngleNE.png    , when: { black:   4, blue: 0, green: '*', red:   8 } }
  - { image: AngleSW.png    , when: { black:   4, blue: 0, green: '*', red:   6 } }
  - { image: AngleSE.png    , when: { black:   4, blue: 0, green: '*', red:   5 } }
  - { image: Out.png        , when: { black:  10, blue: 0, green: '*', red: '*' } }
  - { image: TopEmpty.png   , when: { black: 100, blue: 0, green: '*', red: '*' } }
  - { image: TopEmpty.png   , when: { black: 103, blue: 0, green: '*', red: '*' } }
  - { image: TopEmpty.png   , when: { black: 104, blue: 0, green: '*', red: '*' } }
  - { image: TopSolved.png  , when: { black: 105, blue: 0, green: '*', red:   0 } }
  - { image: TopUnsolved.png, when: { black: 105, blue: 0, green: '*', red: '*' } }
  - { image: TopMin01.png   , when: { black: 102, blue: 0, green: '*', red:   1 } }
  - { image: TopMin02.png   , when: { black: 102, blue: 0, green: '*', red:   2 } }
  - { image: TopMin03.png   , when: { black: 102, blue: 0, green: '*', red:   3 } }
  - { image: TopMin04.png   , when: { black: 102, blue: 0, green: '*', red:   4 } }
  - { image: TopMin05.png   , when: { black: 102, blue: 0, green: '*', red:   5 } }
  - { image: TopMin06.png   , when: { black: 102, blue: 0, green: '*', red:   6 } }
  - { image: TopMin07.png   , when: { black: 102, blue: 0, green: '*', red:   7 } }
  - { image: TopMin08.png   , when: { black: 102, blue: 0, green: '*', red:   8 } }
  - { image: TopMin09.png   , when: { black: 102, blue: 0, green: '*', red:   9 } }
  - { image: TopMin10.png   , when: { black: 102, blue: 0, green: '*', red:  10 } }
  - { image: TopMin11.png   , when: { black: 102, blue: 0, green: '*', red:  11 } }
  - { image: TopMin12.png   , when: { black: 102, blue: 0, green: '*', red:  12 } }
  - { image: TopMin13.png   , when: { black: 102, blue: 0, green: '*', red:  13 } }
  - { image: TopMin14.png   , when: { black: 102, blue: 0, green: '*', red:  14 } }
  - { image: TopMin15.png   , when: { black: 102, blue: 0, green: '*', red:  15 } }
  - { image: TopMin16.png   , when: { black: 102, blue: 0, green: '*', red:  16 } }
  - { image: TopMin17.png   , when: { black: 102, blue: 0, green: '*', red:  17 } }
  - { image: TopMin18.png   , when: { black: 102, blue: 0, green: '*', red:  18 } }
  - { image: TopMin19.png   , when: { black: 102, blue: 0, green: '*', red:  19 } }
  - { image: TopMin20.png   , when: { black: 102, blue: 0, green: '*', red:  20 } }
  - { image: TopMin21.png   , when: { black: 102, blue: 0, green: '*', red:  21 } }
  - { image: TopMin22.png   , when: { black: 102, blue: 0, green: '*', red:  22 } }
  - { image: TopMin23.png   , when: { black: 102, blue: 0, green: '*', red:  23 } }
  - { image: TopMin24.png   , when: { black: 102, blue: 0, green: '*', red:  24 } }
  - { image: TopMin25.png   , when: { black: 102, blue: 0, green: '*', red:  25 } }
  - { image: TopMin26.png   , when: { black: 102, blue: 0, green: '*', red:  26 } }
  - { image: TopMin27.png   , when: { black: 102, blue: 0, green: '*', red:  27 } }
  - { image: TopMin28.png   , when: { black: 102, blue: 0, green: '*', red:  28 } }
  - { image: TopMin29.png   , when: { black: 102, blue: 0, green: '*', red:  29 } }
  - { image: TopEmpty.png   , when: { black: 102, blue: 0, green: '*', red: '*' } }
  - { image: TopNum00.png   , when: { black: 101, blue: 0, green: '*', red:   0 } }
  - { image: TopNum01.png   , when: { black: 101, blue: 0, green: '*', red:   1 } }
  - { image: TopNum02.png   , when: { black: 101, blue: 0, green: '*', red:   2 } }
  - { image: TopNum03.png   , when: { black: 101, blue: 0, green: '*', red:   3 } }
  - { image: TopNum04.png   , when: { black: 101, blue: 0, green: '*', red:   4 } }
  - { image: TopNum05.png   , when: { black: 101, blue: 0, green: '*', red:   5 } }
  - { image: TopNum06.png   , when: { black: 101, blue: 0, green: '*', red:   6 } }
  - { image: TopNum07.png   , when: { black: 101, blue: 0, green: '*', red:   7 } }
  - { image: TopNum08.png   , when: { black: 101, blue: 0, green: '*', red:   8 } }
  - { image: TopNum09.png   , when: { black: 101, blue: 0, green: '*', red:   9 } }
  - { image: TopNum10.png   , when: { black: 101, blue: 0, green: '*', red:  10 } }
  - { image: TopNum11.png   , when: { black: 101, blue: 0, green: '*', red:  11 } }
  - { image: TopNum12.png   , when: { black: 101, blue: 0, green: '*', red:  12 } }
  - { image: TopNum13.png   , when: { black: 101, blue: 0, green: '*', red:  13 } }
  - { image: TopNum14.png   , when: { black: 101, blue: 0, green: '*', red:  14 } }
  - { image: TopNum15.png   , when: { black: 101, blue: 0, green: '*', red:  15 } }
  - { image: TopNum16.png   , when: { black: 101, blue: 0, green: '*', red:  16 } }
  - { image: TopNum17.png   , when: { black: 101, blue: 0, green: '*', red:  17 } }
  - { image: TopNum18.png   , when: { black: 101, blue: 0, green: '*', red:  18 } }
  - { image: TopNum19.png   , when: { black: 101, blue: 0, green: '*', red:  19 } }
  - { image: TopNum20.png   , when: { black: 101, blue: 0, green: '*', red:  20 } }
  - { image: TopNum21.png   , when: { black: 101, blue: 0, green: '*', red:  21 } }
  - { image: TopNum22.png   , when: { black: 101, blue: 0, green: '*', red:  22 } }
  - { image: TopNum23.png   , when: { black: 101, blue: 0, green: '*', red:  23 } }
  - { image: TopNum24.png   , when: { black: 101, blue: 0, green: '*', red:  24 } }
  - { image: TopNum25.png   , when: { black: 101, blue: 0, green: '*', red:  25 } }
  - { image: TopNum26.png   , when: { black: 101, blue: 0, green: '*', red:  26 } }
  - { image: TopNum27.png   , when: { black: 101, blue: 0, green: '*', red:  27 } }
  - { image: TopNum28.png   , when: { black: 101, blue: 0, green: '*', red:  28 } }
  - { image: TopNum29.png   , when: { black: 101, blue: 0, green: '*', red:  29 } }
  - { image: TopNum20.png   , when: { black: 101, blue: 0, green: '*', red:  20 } }
  - { image: TopNum21.png   , when: { black: 101, blue: 0, green: '*', red:  21 } }
  - { image: TopNum22.png   , when: { black: 101, blue: 0, green: '*', red:  22 } }
  - { image: TopNum23.png   , when: { black: 101, blue: 0, green: '*', red:  23 } }
  - { image: TopNum24.png   , when: { black: 101, blue: 0, green: '*', red:  24 } }
  - { image: TopNum25.png   , when: { black: 101, blue: 0, green: '*', red:  25 } }
  - { image: TopNum26.png   , when: { black: 101, blue: 0, green: '*', red:  26 } }
  - { image: TopNum27.png   , when: { black: 101, blue: 0, green: '*', red:  27 } }
  - { image: TopNum28.png   , when: { black: 101, blue: 0, green: '*', red:  28 } }
  - { image: TopNum29.png   , when: { black: 101, blue: 0, green: '*', red:  29 } }
  - { image: TopNum30.png   , when: { black: 101, blue: 0, green: '*', red:  30 } }
  - { image: TopNum31.png   , when: { black: 101, blue: 0, green: '*', red:  31 } }
  - { image: TopNum32.png   , when: { black: 101, blue: 0, green: '*', red:  32 } }
  - { image: TopNum33.png   , when: { black: 101, blue: 0, green: '*', red:  33 } }
  - { image: TopNum34.png   , when: { black: 101, blue: 0, green: '*', red:  34 } }
  - { image: TopNum35.png   , when: { black: 101, blue: 0, green: '*', red:  35 } }
  - { image: TopNum36.png   , when: { black: 101, blue: 0, green: '*', red:  36 } }
  - { image: TopNum37.png   , when: { black: 101, blue: 0, green: '*', red:  37 } }
  - { image: TopNum38.png   , when: { black: 101, blue: 0, green: '*', red:  38 } }
  - { image: TopNum39.png   , when: { black: 101, blue: 0, green: '*', red:  39 } }
  - { image: TopNum40.png   , when: { black: 101, blue: 0, green: '*', red:  40 } }
  - { image: TopNum41.png   , when: { black: 101, blue: 0, green: '*', red:  41 } }
  - { image: TopNum42.png   , when: { black: 101, blue: 0, green: '*', red:  42 } }
  - { image: TopNum43.png   , when: { black: 101, blue: 0, green: '*', red:  43 } }
  - { image: TopNum44.png   , when: { black: 101, blue: 0, green: '*', red:  44 } }
  - { image: TopNum45.png   , when: { black: 101, blue: 0, green: '*', red:  45 } }
  - { image: TopNum46.png   , when: { black: 101, blue: 0, green: '*', red:  46 } }
  - { image: TopNum47.png   , when: { black: 101, blue: 0, green: '*', red:  47 } }
  - { image: TopNum48.png   , when: { black: 101, blue: 0, green: '*', red:  48 } }
  - { image: TopNum49.png   , when: { black: 101, blue: 0, green: '*', red:  49 } }
  - { image: TopNum50.png   , when: { black: 101, blue: 0, green: '*', red:  50 } }
  - { image: TopNum51.png   , when: { black: 101, blue: 0, green: '*', red:  51 } }
  - { image: TopNum52.png   , when: { black: 101, blue: 0, green: '*', red:  52 } }
  - { image: TopNum53.png   , when: { black: 101, blue: 0, green: '*', red:  53 } }
  - { image: TopNum54.png   , when: { black: 101, blue: 0, green: '*', red:  54 } }
  - { image: TopNum55.png   , when: { black: 101, blue: 0, green: '*', red:  55 } }
  - { image: TopNum56.png   , when: { black: 101, blue: 0, green: '*', red:  56 } }
  - { image: TopNum57.png   , when: { black: 101, blue: 0, green: '*', red:  57 } }
  - { image: TopNum58.png   , when: { black: 101, blue: 0, green: '*', red:  58 } }
  - { image: TopNum59.png   , when: { black: 101, blue: 0, green: '*', red:  59 } }
  - { image: TopNum60.png   , when: { black: 101, blue: 0, green: '*', red:  60 } }
  - { image: TopNum61.png   , when: { black: 101, blue: 0, green: '*', red:  61 } }
  - { image: TopNum62.png   , when: { black: 101, blue: 0, green: '*', red:  62 } }
  - { image: TopNum63.png   , when: { black: 101, blue: 0, green: '*', red:  63 } }
  - { image: TopNum64.png   , when: { black: 101, blue: 0, green: '*', red:  64 } }
  - { image: TopNum65.png   , when: { black: 101, blue: 0, green: '*', red:  65 } }
  - { image: TopNum66.png   , when: { black: 101, blue: 0, green: '*', red:  66 } }
  - { image: TopNum67.png   , when: { black: 101, blue: 0, green: '*', red:  67 } }
  - { image: TopNum68.png   , when: { black: 101, blue: 0, green: '*', red:  68 } }
  - { image: TopNum69.png   , when: { black: 101, blue: 0, green: '*', red:  69 } }
  - { image: TopNum70.png   , when: { black: 101, blue: 0, green: '*', red:  70 } }
  - { image: TopNum71.png   , when: { black: 101, blue: 0, green: '*', red:  71 } }
  - { image: TopNum72.png   , when: { black: 101, blue: 0, green: '*', red:  72 } }
  - { image: TopNum73.png   , when: { black: 101, blue: 0, green: '*', red:  73 } }
  - { image: TopNum74.png   , when: { black: 101, blue: 0, green: '*', red:  74 } }
  - { image: TopNum75.png   , when: { black: 101, blue: 0, green: '*', red:  75 } }
  - { image: TopNum76.png   , when: { black: 101, blue: 0, green: '*', red:  76 } }
  - { image: TopNum77.png   , when: { black: 101, blue: 0, green: '*', red:  77 } }
  - { image: TopNum78.png   , when: { black: 101, blue: 0, green: '*', red:  78 } }
  - { image: TopNum79.png   , when: { black: 101, blue: 0, green: '*', red:  79 } }
  - { image: TopNum80.png   , when: { black: 101, blue: 0, green: '*', red:  80 } }
  - { image: TopNum81.png   , when: { black: 101, blue: 0, green: '*', red:  81 } }
  - { image: TopNum82.png   , when: { black: 101, blue: 0, green: '*', red:  82 } }
  - { image: TopNum83.png   , when: { black: 101, blue: 0, green: '*', red:  83 } }
  - { image: TopNum84.png   , when: { black: 101, blue: 0, green: '*', red:  84 } }
  - { image: TopNum85.png   , when: { black: 101, blue: 0, green: '*', red:  85 } }
  - { image: TopNum86.png   , when: { black: 101, blue: 0, green: '*', red:  86 } }
  - { image: TopNum87.png   , when: { black: 101, blue: 0, green: '*', red:  87 } }
  - { image: TopNum88.png   , when: { black: 101, blue: 0, green: '*', red:  88 } }
  - { image: TopNum89.png   , when: { black: 101, blue: 0, green: '*', red:  89 } }
  - { image: TopNum90.png   , when: { black: 101, blue: 0, green: '*', red:  90 } }
  - { image: TopNum91.png   , when: { black: 101, blue: 0, green: '*', red:  91 } }
  - { image: TopNum92.png   , when: { black: 101, blue: 0, green: '*', red:  92 } }
  - { image: TopNum93.png   , when: { black: 101, blue: 0, green: '*', red:  93 } }
  - { image: TopNum94.png   , when: { black: 101, blue: 0, green: '*', red:  94 } }
  - { image: TopNum95.png   , when: { black: 101, blue: 0, green: '*', red:  95 } }
  - { image: TopNum96.png   , when: { black: 101, blue: 0, green: '*', red:  96 } }
  - { image: TopNum97.png   , when: { black: 101, blue: 0, green: '*', red:  97 } }
  - { image: TopNum98.png   , when: { black: 101, blue: 0, green: '*', red:  98 } }
  - { image: TopNum99.png   , when: { black: 101, blue: 0, green: '*', red:  99 } }
  - { image: TopNum99+.png  , when: { black: 101, blue: 0, green: '*', red: '*' } }
