name: Quell
rules:
  - { image: Empty.png     , when: { black: 0, blue: 0, green: 0, red:   0 } }
  - { image: Pearl.png     , when: { black: 1, blue: 0, green: 0, red:   0 } }
  - { image: Wall.png      , when: { black: 2, blue: 0, green: 0, red:   0 } }
  - { image: Wall.png      , when: { black: 2, blue: 0, green: 1, red: '*' } }
