name: Distributing candies
rules:
  - { image: StudentBeforeAndTeacher.png   , when: { black: 2, blue: 0, green: 0, red: 0 } }
  - { image: StudentBefore.png             , when: { black: 0, blue: 0, green: 0, red: 0 } }
  - { image: StudentWithCandyAndTeacher.png, when: { black: 2, blue: 0, green: 1, red: 0 } }
  - { image: StudentWithCandy.png          , when: { black: 0, blue: 0, green: 1, red: 0 } }
  - { image: StudentWithPaperAndTeacher.png, when: { black: 2, blue: 1, green: 0, red: 1 } }
  - { image: StudentWithPaper.png          , when: { black: 0, blue: 1, green: 0, red: 1 } }
  - { image: HappyStudentAndTeacher.png    , when: { black: 2, blue: 1, green: 0, red: 0 } }
  - { image: HappyStudent.png              , when: { black: 0, blue: 1, green: 0, red: 0 } }
  - { image: DeskAndTeacher.png            , when: { black: 3, blue: 0, green: 0, red: 0 } }
  - { image: Desk.png                      , when: { black: 1, blue: 0, green: 0, red: 0 } }
