name: RGB Colors
rules:
  - { image: 0000.png, when: { black:   0, blue: 0, green: 0, red: 0 } }
  - { image: 1000.png, when: { black:   1, blue: 0, green: 0, red: 0 } }
  - { image: 2000.png, when: { black:   2, blue: 0, green: 0, red: 0 } }
  - { image: 3000.png, when: { black:   3, blue: 0, green: 0, red: 0 } }
  - { image: 4000.png, when: { black:   4, blue: 0, green: 0, red: 0 } }
  - { image: 0001.png, when: { black: '*', blue: 1, green: 0, red: 0 } }
  - { image: 0002.png, when: { black: '*', blue: 2, green: 0, red: 0 } }
  - { image: 0003.png, when: { black: '*', blue: 3, green: 0, red: 0 } }
  - { image: 0004.png, when: { black: '*', blue: 4, green: 0, red: 0 } }
  - { image: 0010.png, when: { black: '*', blue: 0, green: 1, red: 0 } }
  - { image: 0011.png, when: { black: '*', blue: 1, green: 1, red: 0 } }
  - { image: 0012.png, when: { black: '*', blue: 2, green: 1, red: 0 } }
  - { image: 0013.png, when: { black: '*', blue: 3, green: 1, red: 0 } }
  - { image: 0014.png, when: { black: '*', blue: 4, green: 1, red: 0 } }
  - { image: 0020.png, when: { black: '*', blue: 0, green: 2, red: 0 } }
  - { image: 0021.png, when: { black: '*', blue: 1, green: 2, red: 0 } }
  - { image: 0022.png, when: { black: '*', blue: 2, green: 2, red: 0 } }
  - { image: 0023.png, when: { black: '*', blue: 3, green: 2, red: 0 } }
  - { image: 0024.png, when: { black: '*', blue: 4, green: 2, red: 0 } }
  - { image: 0030.png, when: { black: '*', blue: 0, green: 3, red: 0 } }
  - { image: 0031.png, when: { black: '*', blue: 1, green: 3, red: 0 } }
  - { image: 0032.png, when: { black: '*', blue: 2, green: 3, red: 0 } }
  - { image: 0033.png, when: { black: '*', blue: 3, green: 3, red: 0 } }
  - { image: 0034.png, when: { black: '*', blue: 4, green: 3, red: 0 } }
  - { image: 0040.png, when: { black: '*', blue: 0, green: 4, red: 0 } }
  - { image: 0041.png, when: { black: '*', blue: 1, green: 4, red: 0 } }
  - { image: 0042.png, when: { black: '*', blue: 2, green: 4, red: 0 } }
  - { image: 0043.png, when: { black: '*', blue: 3, green: 4, red: 0 } }
  - { image: 0044.png, when: { black: '*', blue: 4, green: 4, red: 0 } }
  - { image: 0100.png, when: { black: '*', blue: 0, green: 0, red: 1 } }
  - { image: 0101.png, when: { black: '*', blue: 1, green: 0, red: 1 } }
  - { image: 0102.png, when: { black: '*', blue: 2, green: 0, red: 1 } }
  - { image: 0103.png, when: { black: '*', blue: 3, green: 0, red: 1 } }
  - { image: 0104.png, when: { black: '*', blue: 4, green: 0, red: 1 } }
  - { image: 0110.png, when: { black: '*', blue: 0, green: 1, red: 1 } }
  - { image: 0111.png, when: { black: '*', blue: 1, green: 1, red: 1 } }
  - { image: 0112.png, when: { black: '*', blue: 2, green: 1, red: 1 } }
  - { image: 0113.png, when: { black: '*', blue: 3, green: 1, red: 1 } }
  - { image: 0114.png, when: { black: '*', blue: 4, green: 1, red: 1 } }
  - { image: 0120.png, when: { black: '*', blue: 0, green: 2, red: 1 } }
  - { image: 0121.png, when: { black: '*', blue: 1, green: 2, red: 1 } }
  - { image: 0122.png, when: { black: '*', blue: 2, green: 2, red: 1 } }
  - { image: 0123.png, when: { black: '*', blue: 3, green: 2, red: 1 } }
  - { image: 0124.png, when: { black: '*', blue: 4, green: 2, red: 1 } }
  - { image: 0130.png, when: { black: '*', blue: 0, green: 3, red: 1 } }
  - { image: 0131.png, when: { black: '*', blue: 1, green: 3, red: 1 } }
  - { image: 0132.png, when: { black: '*', blue: 2, green: 3, red: 1 } }
  - { image: 0133.png, when: { black: '*', blue: 3, green: 3, red: 1 } }
  - { image: 0134.png, when: { black: '*', blue: 4, green: 3, red: 1 } }
  - { image: 0140.png, when: { black: '*', blue: 0, green: 4, red: 1 } }
  - { image: 0141.png, when: { black: '*', blue: 1, green: 4, red: 1 } }
  - { image: 0142.png, when: { black: '*', blue: 2, green: 4, red: 1 } }
  - { image: 0143.png, when: { black: '*', blue: 3, green: 4, red: 1 } }
  - { image: 0144.png, when: { black: '*', blue: 4, green: 4, red: 1 } }
  - { image: 0200.png, when: { black: '*', blue: 0, green: 0, red: 2 } }
  - { image: 0201.png, when: { black: '*', blue: 1, green: 0, red: 2 } }
  - { image: 0202.png, when: { black: '*', blue: 2, green: 0, red: 2 } }
  - { image: 0203.png, when: { black: '*', blue: 3, green: 0, red: 2 } }
  - { image: 0204.png, when: { black: '*', blue: 4, green: 0, red: 2 } }
  - { image: 0210.png, when: { black: '*', blue: 0, green: 1, red: 2 } }
  - { image: 0211.png, when: { black: '*', blue: 1, green: 1, red: 2 } }
  - { image: 0212.png, when: { black: '*', blue: 2, green: 1, red: 2 } }
  - { image: 0213.png, when: { black: '*', blue: 3, green: 1, red: 2 } }
  - { image: 0214.png, when: { black: '*', blue: 4, green: 1, red: 2 } }
  - { image: 0220.png, when: { black: '*', blue: 0, green: 2, red: 2 } }
  - { image: 0221.png, when: { black: '*', blue: 1, green: 2, red: 2 } }
  - { image: 0222.png, when: { black: '*', blue: 2, green: 2, red: 2 } }
  - { image: 0223.png, when: { black: '*', blue: 3, green: 2, red: 2 } }
  - { image: 0224.png, when: { black: '*', blue: 4, green: 2, red: 2 } }
  - { image: 0230.png, when: { black: '*', blue: 0, green: 3, red: 2 } }
  - { image: 0231.png, when: { black: '*', blue: 1, green: 3, red: 2 } }
  - { image: 0232.png, when: { black: '*', blue: 2, green: 3, red: 2 } }
  - { image: 0233.png, when: { black: '*', blue: 3, green: 3, red: 2 } }
  - { image: 0234.png, when: { black: '*', blue: 4, green: 3, red: 2 } }
  - { image: 0240.png, when: { black: '*', blue: 0, green: 4, red: 2 } }
  - { image: 0241.png, when: { black: '*', blue: 1, green: 4, red: 2 } }
  - { image: 0242.png, when: { black: '*', blue: 2, green: 4, red: 2 } }
  - { image: 0243.png, when: { black: '*', blue: 3, green: 4, red: 2 } }
  - { image: 0244.png, when: { black: '*', blue: 4, green: 4, red: 2 } }
  - { image: 0300.png, when: { black: '*', blue: 0, green: 0, red: 3 } }
  - { image: 0301.png, when: { black: '*', blue: 1, green: 0, red: 3 } }
  - { image: 0302.png, when: { black: '*', blue: 2, green: 0, red: 3 } }
  - { image: 0303.png, when: { black: '*', blue: 3, green: 0, red: 3 } }
  - { image: 0304.png, when: { black: '*', blue: 4, green: 0, red: 3 } }
  - { image: 0310.png, when: { black: '*', blue: 0, green: 1, red: 3 } }
  - { image: 0311.png, when: { black: '*', blue: 1, green: 1, red: 3 } }
  - { image: 0312.png, when: { black: '*', blue: 2, green: 1, red: 3 } }
  - { image: 0313.png, when: { black: '*', blue: 3, green: 1, red: 3 } }
  - { image: 0314.png, when: { black: '*', blue: 4, green: 1, red: 3 } }
  - { image: 0320.png, when: { black: '*', blue: 0, green: 2, red: 3 } }
  - { image: 0321.png, when: { black: '*', blue: 1, green: 2, red: 3 } }
  - { image: 0322.png, when: { black: '*', blue: 2, green: 2, red: 3 } }
  - { image: 0323.png, when: { black: '*', blue: 3, green: 2, red: 3 } }
  - { image: 0324.png, when: { black: '*', blue: 4, green: 2, red: 3 } }
  - { image: 0330.png, when: { black: '*', blue: 0, green: 3, red: 3 } }
  - { image: 0331.png, when: { black: '*', blue: 1, green: 3, red: 3 } }
  - { image: 0332.png, when: { black: '*', blue: 2, green: 3, red: 3 } }
  - { image: 0333.png, when: { black: '*', blue: 3, green: 3, red: 3 } }
  - { image: 0334.png, when: { black: '*', blue: 4, green: 3, red: 3 } }
  - { image: 0340.png, when: { black: '*', blue: 0, green: 4, red: 3 } }
  - { image: 0341.png, when: { black: '*', blue: 1, green: 4, red: 3 } }
  - { image: 0342.png, when: { black: '*', blue: 2, green: 4, red: 3 } }
  - { image: 0343.png, when: { black: '*', blue: 3, green: 4, red: 3 } }
  - { image: 0344.png, when: { black: '*', blue: 4, green: 4, red: 3 } }
  - { image: 0400.png, when: { black: '*', blue: 0, green: 0, red: 4 } }
  - { image: 0401.png, when: { black: '*', blue: 1, green: 0, red: 4 } }
  - { image: 0402.png, when: { black: '*', blue: 2, green: 0, red: 4 } }
  - { image: 0403.png, when: { black: '*', blue: 3, green: 0, red: 4 } }
  - { image: 0404.png, when: { black: '*', blue: 4, green: 0, red: 4 } }
  - { image: 0410.png, when: { black: '*', blue: 0, green: 1, red: 4 } }
  - { image: 0411.png, when: { black: '*', blue: 1, green: 1, red: 4 } }
  - { image: 0412.png, when: { black: '*', blue: 2, green: 1, red: 4 } }
  - { image: 0413.png, when: { black: '*', blue: 3, green: 1, red: 4 } }
  - { image: 0414.png, when: { black: '*', blue: 4, green: 1, red: 4 } }
  - { image: 0420.png, when: { black: '*', blue: 0, green: 2, red: 4 } }
  - { image: 0421.png, when: { black: '*', blue: 1, green: 2, red: 4 } }
  - { image: 0422.png, when: { black: '*', blue: 2, green: 2, red: 4 } }
  - { image: 0423.png, when: { black: '*', blue: 3, green: 2, red: 4 } }
  - { image: 0424.png, when: { black: '*', blue: 4, green: 2, red: 4 } }
  - { image: 0430.png, when: { black: '*', blue: 0, green: 3, red: 4 } }
  - { image: 0431.png, when: { black: '*', blue: 1, green: 3, red: 4 } }
  - { image: 0432.png, when: { black: '*', blue: 2, green: 3, red: 4 } }
  - { image: 0433.png, when: { black: '*', blue: 3, green: 3, red: 4 } }
  - { image: 0434.png, when: { black: '*', blue: 4, green: 3, red: 4 } }
  - { image: 0440.png, when: { black: '*', blue: 0, green: 4, red: 4 } }
  - { image: 0441.png, when: { black: '*', blue: 1, green: 4, red: 4 } }
  - { image: 0442.png, when: { black: '*', blue: 2, green: 4, red: 4 } }
  - { image: 0443.png, when: { black: '*', blue: 3, green: 4, red: 4 } }
  - { image: 0444.png, when: { black: '*', blue: 4, green: 4, red: 4 } }
